package com.tiger.compiler.parser;

import com.tiger.compiler.parser.GrammarToken;

public enum Nonterminal implements GrammarToken {
	TIGER_PROGRAM, DECLARATION_STAT, TYPE_DECL_LIST, VAR_DECL_LIST,
	TYPE_DECL, VAR_DECL, FUNCT_DECL_LIST, FUNCT_DECL, TYPE_P,
	TYPE_ID, FIELD_LIST, ID_LIST, ID_LIST_TAIL, OPTIONAL_INIT, PARAM_LIST,
	PARAM_LIST_TAIL, PARAM, RET_TYPE, STAT_SEQ, STAT_SEQ_TAIL, STAT,
	STAT_SEQ_IF_ENDIF_TAIL, F_OR_A_STAT, RHS_ASSIGN, F_OR_E_STAT,
	LVALUE, LVALUE_TAIL, EXPR, EXPRPRIME, EXPR0, EXPR0PRIME, TERM1,
	TERM1PRIME, TERM2, TERM2PRIME, TERM3, TERM3PRIME, TERM4, TERM4PRIME,
	TERM5, OP0, OP1, OP2, OP3, CONST, EXPR_LIST, EXPR_LIST_TAIL, OPERATOR;
}